### ISSUE TITLE
example routes.csv needed

### ISSUE THREAD

**Issue by mhglover** [jachee/dashboard#1]
Needs an example of the routes.csv file.  Maybe add routes.csv.sample and add *.csv to .gitignore?  Also documentation in readme.md on how to generate a routes.csv file.

**Comment by jachee** [comment]
I'll update the readme in a bit. 😄

**Comment by jachee** [comment]
"A bit" is apparently just over a month, but it's been done.  Commit 0c93832f3245205011e9de8cf2cd77ad391406bb resolves this issuse.
